title: [Fanibhusana Maharana]
logo: /img/profile-pic (15).png
description: [Passionate about using technology to solve real-world problems. Proficient in Core Java, Advanced Java, JavaFX, MySQL, HTML, C programming, DSA, and Spring Boot]
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
